# Site Settings
title: Krishna Mohans's Blog
email: krishnamohan.a.m@live.in
description: I am yet to figure it out.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"

# User Settings
username: Krishna Mohan
user_description: Code | Football | Movies
# disqus_username: disqus_username

# Social Media
# Remove the item if you don't need it
github_username: krishnaanaril
facebook_username: krishnaanaril
twitter_username: krishnaanaril
instagram_username: krishnaanaril
# linkedin_username: linkedin_username
medium_username: krishnaanaril

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
